// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwstjvSpHuwVJAK9cPbf3LjuLOpM1zjk',
    appId: '1:667133118764:android:895b5684bddc076b368489',
    messagingSenderId: '667133118764',
    projectId: 'snapsticker-9c910',
    storageBucket: 'snapsticker-9c910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHgkp-3gRPvgVyW6uWUBP8y_1IpFYmY4',
    appId: '1:667133118764:ios:ee2087346599f35d368489',
    messagingSenderId: '667133118764',
    projectId: 'snapsticker-9c910',
    storageBucket: 'snapsticker-9c910.firebasestorage.app',
    androidClientId: '667133118764-db12tj0gbho29h8i70o5vmknr9kd3is8.apps.googleusercontent.com',
    iosClientId: '667133118764-8739jncseec4584fh80u8n1tgcil0rd3.apps.googleusercontent.com',
    iosBundleId: 'com.sazid.snapsticker',
  );

}